<a href="https://colab.research.google.com/github/isfandyr/118_Bootstrap_Muhammad-Adrianto/blob/main/Tugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
import numpy as np
import pandas as pd

In [12]:
ds = pd.read_csv('/content/drive/MyDrive/Tugas/Data Intelligent Irrigation System.csv')
ds

crop  moisture  temp  pump
0    cotton       638    16     1
1    cotton       522    18     1
2    cotton       741    22     1
3    cotton       798    32     1
4    cotton       690    28     1
..      ...       ...   ...   ...
195  cotton       941    13     1
196  cotton       902    45     1
197  cotton       894    42     1
198  cotton      1022    45     1
199  cotton       979    10     1

[200 rows x 4 columns]

In [13]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   crop      200 non-null    object
 1   moisture  200 non-null    int64 
 2   temp      200 non-null    int64 
 3   pump      200 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 6.4+ KB


In [14]:
x = ds.iloc[:,[1,2]].values
y = ds.iloc[:, -1].values

In [15]:
x

array([[ 638,   16],
       [ 522,   18],
       [ 741,   22],
       [ 798,   32],
       [ 690,   28],
       [ 558,   23],
       [ 578,   12],
       [ 673,   35],
       [ 642,   45],
       [ 723,   11],
       [ 671,   23],
       [ 758,   34],
       [ 507,   45],
       [ 586,   33],
       [ 703,   45],
       [ 716,   25],
       [ 724,   11],
       [ 828,   41],
       [ 633,   23],
       [ 783,   18],
       [ 635,   36],
       [ 525,   33],
       [ 636,   24],
       [ 813,   15],
       [ 736,   44],
       [ 833,   13],
       [ 808,   29],
       [ 714,   14],
       [ 806,   28],
       [ 681,   31],
       [ 661,   35],
       [ 546,   32],
       [ 759,   10],
       [ 803,   21],
       [ 670,   22],
       [ 796,   21],
       [ 665,   32],
       [ 687,   11],
       [ 573,   13],
       [ 812,   38],
       [ 698,   45],
       [ 675,   39],
       [ 700,   38],
       [ 749,   38],
       [ 537,   44],
       [ 748,   27],
       [ 824,   37],
       [ 839,

In [16]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [17]:
from sklearn.model_selection import train_test_split #membagi data train dan tes
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0) #variabel baru
print(x_train)

[[ 637   29]
 [ 175   15]
 [ 888   44]
 [ 837   30]
 [  74   20]
 [ 736   44]
 [ 661   35]
 [ 926   18]
 [ 698   45]
 [ 535   17]
 [ 209   43]
 [ 553   35]
 [ 872   10]
 [ 783   18]
 [1019   37]
 [ 795   15]
 [ 580   14]
 [ 922   23]
 [ 663   24]
 [ 699   22]
 [ 178   39]
 [ 850   16]
 [  72   13]
 [  76   35]
 [  59   20]
 [ 545   29]
 [ 168   10]
 [ 703   45]
 [ 714   14]
 [  39   38]
 [ 974   28]
 [ 824   37]
 [   4   42]
 [ 941   13]
 [ 482   27]
 [ 659   29]
 [ 741   22]
 [ 788   12]
 [  87   12]
 [ 894   42]
 [ 749   38]
 [ 671   23]
 [ 914   35]
 [ 611   12]
 [ 902   45]
 [1005   43]
 [1010   10]
 [ 354   20]
 [ 817   18]
 [ 306   25]
 [ 865   17]
 [ 986   36]
 [ 775   40]
 [ 638   16]
 [ 830   44]
 [ 208   39]
 [ 843   41]
 [ 641   35]
 [1001   36]
 [ 675   39]
 [ 509   19]
 [ 533   42]
 [ 740   31]
 [ 737   34]
 [ 586   33]
 [ 923   10]
 [ 813   15]
 [ 917   33]
 [ 302   23]
 [ 635   36]
 [ 716   25]
 [ 683   39]
 [ 493   18]
 [ 639   14]
 [  89   42]
 [ 539   26]
 [ 798   32]

In [18]:
len(x_train) #total yang sudah dibagi untuk train

150

In [19]:
len(x) #total semua data sebelum dibagi

200

In [20]:
len(x_test) #total test

50

In [21]:
print(y_train)

[1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 1 1
 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1
 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0
 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0
 1 1]


In [22]:
len(y_train)

150

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train1 = sc.fit_transform(x_train)
x_test1 = sc.fit_transform(x_test)

In [24]:
print(x_train1)

[[-0.02646906  0.14049224]
 [-1.68948442 -1.14226299]
 [ 0.87703063  1.51487285]
 [ 0.69345101  0.23211761]
 [-2.05304406 -0.68413612]
 [ 0.32989137  1.51487285]
 [ 0.05992135  0.69024448]
 [ 1.01381544 -0.86738687]
 [ 0.19310656  1.60649822]
 [-0.3936283  -0.95901225]
 [-1.56709801  1.42324747]
 [-0.32883549  0.69024448]
 [ 0.81943702 -1.60038986]
 [ 0.49907259 -0.86738687]
 [ 1.34857827  0.87349523]
 [ 0.54226779 -1.14226299]
 [-0.23164628 -1.23388837]
 [ 0.99941704 -0.40926   ]
 [ 0.06712055 -0.31763463]
 [ 0.19670616 -0.50088538]
 [-1.67868562  1.05674598]
 [ 0.74024581 -1.05063762]
 [-2.06024326 -1.32551374]
 [-2.04584486  0.69024448]
 [-2.10703806 -0.68413612]
 [-0.35763229  0.14049224]
 [-1.71468162 -1.60038986]
 [ 0.21110456  1.60649822]
 [ 0.25070017 -1.23388837]
 [-2.17903007  0.9651206 ]
 [ 1.18659626  0.04886687]
 [ 0.6466562   0.87349523]
 [-2.30501608  1.3316221 ]
 [ 1.06780944 -1.32551374]
 [-0.58440712 -0.04275851]
 [ 0.05272215  0.14049224]
 [ 0.34788938 -0.50088538]
 

In [25]:
x_train1

array([[-0.02646906,  0.14049224],
       [-1.68948442, -1.14226299],
       [ 0.87703063,  1.51487285],
       [ 0.69345101,  0.23211761],
       [-2.05304406, -0.68413612],
       [ 0.32989137,  1.51487285],
       [ 0.05992135,  0.69024448],
       [ 1.01381544, -0.86738687],
       [ 0.19310656,  1.60649822],
       [-0.3936283 , -0.95901225],
       [-1.56709801,  1.42324747],
       [-0.32883549,  0.69024448],
       [ 0.81943702, -1.60038986],
       [ 0.49907259, -0.86738687],
       [ 1.34857827,  0.87349523],
       [ 0.54226779, -1.14226299],
       [-0.23164628, -1.23388837],
       [ 0.99941704, -0.40926   ],
       [ 0.06712055, -0.31763463],
       [ 0.19670616, -0.50088538],
       [-1.67868562,  1.05674598],
       [ 0.74024581, -1.05063762],
       [-2.06024326, -1.32551374],
       [-2.04584486,  0.69024448],
       [-2.10703806, -0.68413612],
       [-0.35763229,  0.14049224],
       [-1.71468162, -1.60038986],
       [ 0.21110456,  1.60649822],
       [ 0.25070017,

In [26]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train1, y_train)


KNeighborsClassifier()

In [27]:
y_pred = classifier.predict(x_test)

In [28]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [29]:
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 0, 14],
       [ 0, 36]])

In [31]:
from sklearn.metrics import classification_report
akurasi = classification_report(y_test, y_pred)
print (akurasi)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.72      1.00      0.84        36

    accuracy                           0.72        50
   macro avg       0.36      0.50      0.42        50
weighted avg       0.52      0.72      0.60        50



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min()-1, stop = x_set[:, 0].max()+1, step = 0.01),
                     np.arange(start = x_set[:, 1].min()-1, stop = x_set[:, 0].max()+1, step = 0.01))
plt.contourf(x1, x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape), alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())
for i, j in enumerate (np.unique(y_set)):
    plt.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Klasifikasi Data dengan K-Nearest Neighbor')
plt.xlabel('Moisture')
plt.ylabel('Temp')
plt.legend()
plt.show()